### ISSUE TITLE
SSL API Calls

### ISSUE THREAD

**Issue by solracsf** [quickemailverification/quickemailverification-php#1]
Can API calls be made trough SSL ?
Even the website dashboard is not accepting SSL (https) connections...

Thanks.

**Comment by twa-team** [comment]
Hello!

Sorry but currently we don't have SSL set for this. We are going to set it up for all domains in near future.

Thanks

**Comment by solracsf** [comment]
OK, since we use HSTS for whole systems, we can't use the API until this is implemented.

**Comment by twa-team** [comment]
Hello,

Our entire website and all API endpoint are SSL secured for last two years now.

Thanks
