### ISSUE TITLE
guzzle dependency

### ISSUE THREAD

**Issue by kcassam** [quickemailverification/quickemailverification-php#2]
could you open authorized version for guzzle ? https://github.com/quickemailverification/quickemailverification-php/blob/master/composer.json#L21 

Some projects use more recent version, example https://github.com/mailjet/mailjet-apiv3-php/blob/master/composer.json and we enter dependency hell.

**Comment by twa-team** [comment]
Guzzle version is updated with latest version support. Could you please check with new release of library ?
