### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by Abhishek-plivo** [quickemailverification/quickemailverification-php#3]
i am using the api in the frontend in Javascript but whenever i am making the api call, i get this msg 
`Fetch API cannot load https://api.quickemailverification.com/v1/verify?email=someEmail&apikey=mykey. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://quickemailverification.com' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` 

Is it possible to use this api for frontend ? If yes , then please help me with the solution

Thanks in advance

**Comment by twa-team** [comment]
Since CORS is not enabled, this API endpoint doesn't work with Javascript in frontend. We recommend to use this API with backend scripts.

**Comment by Abhishek-plivo** [comment]
Thanks for the clarification 👍
